import {
  BugElement,
  DarkElement,
  DragonElement,
  ElectricElement,
  FairyElement,
  FightingElement,
  FireElement,
  FlyingElement,
  GhostElement,
  GrassElement,
  GroundElement,
  IceElement,
  NormalElement,
  PoisonElement,
  PsychicElement,
  SteelElement,
  RockElement,
  WaterElement,
} from '../assets/logo';

export const Elements = {
  bug: BugElement,
  dark: DarkElement,
  dragon: DragonElement,
  electric: ElectricElement,
  fairy: FairyElement,
  fighting: FightingElement,
  fire: FireElement,
  flying: FlyingElement,
  ghost: GhostElement,
  grass: GrassElement,
  ground: GroundElement,
  ice: IceElement,
  normal: NormalElement,
  poison: PoisonElement,
  psychic: PsychicElement,
  steel: SteelElement,
  rock: RockElement,
  water: WaterElement,
};
